### ISSUE TITLE
模态窗口运行时，疯狂右键托盘，会出现crash

### ISSUE THREAD

**Issue by shywon** [MRXY001/Qt-FacileMenu#2]
你好，我在使用FacileMenu时遇到了崩溃。
复现步骤：当有一个模态窗口运行时，右键托盘（多试几次）FacileMenu::execute()会出现崩溃

crash出现在
QPixmap pixmap = bg;

**Comment by iwxyi** [comment]
这句话应该不会引起崩溃，可能是其他地方出了问题，刚好执行到这一句？
如果是从菜单中打开新的模态窗口，需要在打开前先执行 `menu->close()`。
（README最后面的[注意点](https://github.com/iwxyi/Qt-FacileMenu#%E6%89%93%E5%BC%80%E6%A8%A1%E6%80%81%E5%AF%B9%E8%AF%9D%E6%A1%86%E5%8F%AF%E8%83%BD%E4%BC%9A%E5%BC%95%E8%B5%B7%E5%B4%A9%E6%BA%83)有写）
