### ISSUE TITLE
你好，我这里menu崩溃问题是由于QApplication::screenAt(QCursor::pos());偶尔为空指针导致的

### ISSUE THREAD

**Issue by shywon** [MRXY001/Qt-FacileMenu#3]
// 是否捕获背景模糊图片
	if (blur_bg_alpha > 0)
	{

		QScreen* screen = QApplication::screenAt(QCursor::pos());
		if (screen) {
		
}
	}

**Comment by iwxyi** [comment]
不知道screen为什么偶尔是空的，不过已经加上判断了
