### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Teacher-May** [MRXY001/Qt-FacileMenu#4]
菜单做得非常好,也非常好用,我个人有些建议:
1. 菜单的动画是从上往下的,能不能添加从下往上的,因为有些时候按钮在底部,弹出时动画从上往下看起来效果不好.
2. 同一个菜单按钮,重复点击的话目前是重新弹出menu,建议改成重复点击时进行弹出和关闭,参考windows的菜单按钮

期待你的更新.

**Comment by iwxyi** [comment]
1.菜单有从下往上的动画
2.展开子菜单不需要点击，移开自动取消，还可以单独响应点击事件

Teacher-May ***@***.***> 于 2023年1月1日周日 下午3:12写道：

**Comment by Teacher-May** [comment]
更新了吗?我好像没找到"从下往上的动画"在哪里设置?

或者直接show me the code  : )

**Comment by iwxyi** [comment]
你看默认的demo，窗口移到下面的时候菜单出现在按钮的上方，动画从下往上出现的

Teacher-May ***@***.***> 于 2023年2月1日周三 下午1:26写道：

**Comment by Teacher-May** [comment]
好像知道了:)
